trigger:
- dockertest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'laravel'  # Replace with your DockerHub service connection name
  imageName: 'laravel'  # Replace with your DockerHub repository name

stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(imageName):$(tag)'
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: 'push'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: '$(tag)'
