trigger:
- main

variables:
  dockerRegistryServiceConnection: 'laravel'  # Update with your DockerHub service connection name
  imageName: 'mohan0736/laravel'
  tagName: 'latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        containerRegistry: $(dockerRegistryServiceConnection)
        dockerfile: '**/Dockerfile'  # Adjust path if necessary
        tags: |
          $(imageName):$(tagName)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: 'push'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(tagName)
