trigger:
- dockertest

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'laravel'  # DockerHub service connection name
  imageName: 'mohan0736/laravel'  # DockerHub repository name
  tagName: 'latest'  # Tag name for the image

stages:
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: 'build'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageName):$(tagName)  # Tag image as 'latest'
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: 'push'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(tagName)  # Push image with 'latest' tag
