services:

mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jenkins_laravel
    ports:
    - 3306:3306
    
  web :
     image : ditinusdevops/devops-test-1:tagname:test2
     ports :
         - "8083:80"
   phpmyadmin:
     image: phpmyadmin:latest
     ports:
       - 8084:80
     environment:
      - PMA_ARBITRARY=1
