version: "3.3"
services:
  web :
    build: .
    ports:
      - "8083:80"
  
  mysql_db:
    image: mysql:8.0
      environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jenkins_laravel
     ports:
      - "3306:3306"
    
  phpmyadmin:
     image: phpmyadmin:latest
     ports:
       - "9001:80"
     environment:
       - PMA_ARBITRARY=1
