version: "3.6"
services:
    php:
        build: .
        restart: always
        ports:
            - "8083:80"
        volumes:
            - .:/var/www/html/
    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=myDb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8084:80
        environment:
            - PMA_HOST=mysql
volumes:
    persistent:
