version: "3.3"
services:
    www:
        build: .
        container_name: webhost
        ports: 
            - "8083:80"
        volumes:
            - ./devops-test:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        restart: always
        container_name: DataBaseServer
        ports: 
            - "3306:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password    
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: PHP_MySQL
        links: 
            - db:db
        ports:
            - 8084:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
